"""Ultra-basic English closed-class words that adults already know.

These are filtered out of the learning queue so sessions start with useful
vocabulary instead of "the / on / and / I".
"""

# Articles, pronouns, basic prepositions, conjunctions, auxiliaries,
# determiners, and other function words — not content vocabulary.
SKIP_BASIC_LEMMAS: frozenset[str] = frozenset(
    {
        # articles / determiners
        "a",
        "an",
        "the",
        "this",
        "that",
        "these",
        "those",
        "all",
        "some",
        "any",
        "no",
        "not",
        "every",
        "each",
        "both",
        "few",
        "many",
        "much",
        "most",
        "other",
        "another",
        "such",
        "own",
        "same",
        "very",
        "just",
        "only",
        "also",
        "more",
        "less",
        # pronouns
        "i",
        "you",
        "he",
        "she",
        "it",
        "we",
        "they",
        "me",
        "him",
        "her",
        "us",
        "them",
        "my",
        "your",
        "his",
        "its",
        "our",
        "their",
        "mine",
        "yours",
        "hers",
        "ours",
        "theirs",
        "myself",
        "yourself",
        "himself",
        "herself",
        "itself",
        "ourselves",
        "themselves",
        "who",
        "whom",
        "whose",
        "which",
        "what",
        "where",
        "when",
        "why",
        "how",
        # basic prepositions
        "to",
        "of",
        "in",
        "on",
        "at",
        "for",
        "with",
        "by",
        "from",
        "up",
        "out",
        "about",
        "into",
        "over",
        "after",
        "before",
        "than",
        "as",
        "between",
        "under",
        "through",
        "during",
        "without",
        "within",
        "along",
        "across",
        "around",
        "against",
        "among",
        "beside",
        "near",
        "above",
        "below",
        "off",
        "down",
        # conjunctions
        "and",
        "but",
        "or",
        "so",
        "if",
        "because",
        "because of",
        "while",
        "although",
        "though",
        "unless",
        "until",
        "since",
        "whether",
        "nor",
        "yet",
        # auxiliaries / modals / be-have-do
        "be",
        "am",
        "is",
        "are",
        "was",
        "were",
        "been",
        "being",
        "have",
        "has",
        "had",
        "having",
        "do",
        "does",
        "did",
        "done",
        "doing",
        "will",
        "would",
        "can",
        "could",
        "shall",
        "should",
        "may",
        "might",
        "must",
        "ought",
        # filler / discourse
        "there",
        "here",
        "then",
        "now",
        "yes",
        "yeah",
        "ok",
        "okay",
        "oh",
        "well",
        "too",
        "either",
        "neither",
        "one",  # pronoun/numeral filler in beginner drills
    }
)


def is_basic_lemma(lemma: str | None) -> bool:
    if not lemma:
        return False
    return lemma.strip().lower() in SKIP_BASIC_LEMMAS
