services:
  livekit:
    container_name: dil-programi-livekit
    image: livekit/livekit-server
    command: --config /etc/livekit.yaml
    ports:
      - "7890:7890"
      - "7891:7891"
      - "7892:7892/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml

  qdrant:
    container_name: dil-programi-qdrant
    image: qdrant/qdrant:v1.14.1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
